version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/news-app
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
